FROM nginx:stable-alpine
COPY ./config/nginx/conf.d /etc/nginx/conf.d
COPY ./frontend/gui/build /usr/share/nginx/html
COPY ./greenhouse/static/ /usr/share/nginx/html/static
CMD ["nginx", "-g", "daemon off;"]