# Generated by Django 3.1 on 2021-06-16 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bio_market', '0003_wallet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='wallet',
        ),
    ]
