# Generated by Django 3.1 on 2021-06-17 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio_market', '0005_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_location',
            field=models.CharField(default='hello', max_length=300),
        ),
    ]
